[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "99abe052c10d12b63714e646705235d325859a2c"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "2b81c10857a505c955d0fa31a211d853427c89b722fea97018d8949f152a549a"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.arm-linux-musleabihf.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "2a65ce2fed13e6efc9449993445c279185225713"
os = "windows"

    [[libvorbis.download]]
    sha256 = "ff084beec0e91e141293c7d7380d52860c168bbbeea3452a1c795a76cfc3d4df"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.i686-w64-mingw32.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "25ff8636c4f09ed1572cb32f4e479b37ac3869b0"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "ba976d5a4d13770c1fd09e61333c3f4f55c5c91655330f8d47e13c9d7fae4f02"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.i686-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "d9dce2261ffb86b1d1759151705a32da472876f4"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "98e5099fc3505262aaa86f438c84aaee534ad37a19563a75bd358eba6de725f5"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.x86_64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "d4494e8104ce1d1d7bc68f515f959bae55db3111"
os = "macos"

    [[libvorbis.download]]
    sha256 = "e2d1dc92c15a323e00c205923bd4d3805f512bb8c8c812ca368b877eafd1f480"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.x86_64-apple-darwin14.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "355505951c27280e06290d4b764d28666b83ce7a"
os = "freebsd"

    [[libvorbis.download]]
    sha256 = "ea803222a8b09a585900d67fdb52208fda818a96e2555c61741e01286ec94565"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.x86_64-unknown-freebsd11.1.tar.gz"
[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "f1b7517ec4f0313b51e2899f6f9d42c5619de768"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "538f6b6f243c101d59e2fa86d125b4352c31a3b814bc0524556f275256a0b571"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.arm-linux-gnueabihf.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "21b96e98a89204de5a1052d0a3fc2b40bb3e376c"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "d6fdf76e9da96111544efc4e7ee216e6452a314d7d15f712d337673ca9a1259a"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.x86_64-linux-musl.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "6ba2ff0dddb57a005ae2625940665acd88f41438"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "b45bebbd54507021e026cd72050c0d9513a09e2b51b855277c788af4392eae9b"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.i686-linux-musl.tar.gz"
[[libvorbis]]
arch = "powerpc64le"
git-tree-sha1 = "75c16d4f4c53a2087cf6ce4a8d412cf5eea343d7"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "2e8b276443e9fe4498ae287aec089b4b989209baa7c065fc032562586c86056a"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.powerpc64le-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "eb5abb4ca36fe6297c9a9731cb5d0549a1c0748d"
os = "windows"

    [[libvorbis.download]]
    sha256 = "83da4438097a182a9bc9a0f0f9b8c74c5aae3e013257494632c0568925d6b264"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.x86_64-w64-mingw32.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "8935c89283c9c89fd8e7e98c7989ebdb0e73086f"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "87537281f10ccc7b319aea4987e2faed7b03e8122d543bff2e0f67bb239cb429"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.aarch64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "33edb7207761846c6c03f6254652882af486089b"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "87b9569d1a34fa127bbf42f6c5b13923dd410b5e688218809fb01bb0172d1c3b"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+1/libvorbis.v1.3.6.aarch64-linux-musl.tar.gz"
